-- Backup of [tb_hazard_factor] from yescoSHE_lab2  (2026-06-22, orphan table backup before DROP)
-- Restore: run schema then data. For checklist, run 01_master before 02_item (FK).
SET NOCOUNT ON;
GO
IF OBJECT_ID('tb_hazard_factor','U') IS NOT NULL
    PRINT 'WARNING: tb_hazard_factor already exists - review before running';
GO
CREATE TABLE [tb_hazard_factor] (
    [id] bigint IDENTITY(1,1) NOT NULL,
    [hazard_type] nvarchar(20) NOT NULL,
    [factor_name] nvarchar(200) NOT NULL,
    [category] nvarchar(100) NULL,
    [process] nvarchar(200) NULL,
    [risk_level] nvarchar(20) NULL,
    [measured_value] nvarchar(100) NULL,
    [exposure_standard] nvarchar(100) NULL,
    [assessment_method] nvarchar(100) NULL,
    [assessment_score] nvarchar(50) NULL,
    [cas_number] nvarchar(50) NULL,
    [exposure_route] nvarchar(100) NULL,
    [vaccination_status] nvarchar(50) NULL,
    [target_group] nvarchar(200) NULL,
    [target_count] int NULL,
    [high_risk_count] int NULL,
    [prevention_status] nvarchar(20) NULL,
    [prevention_detail] nvarchar(MAX) NULL,
    [prevention_rate] int NULL DEFAULT ((0)),
    [last_check_date] date NULL,
    [manager_name] nvarchar(100) NULL,
    [manager_dept] nvarchar(100) NULL,
    [remarks] nvarchar(MAX) NULL,
    [created_at] datetime2(7) NULL DEFAULT (getdate()),
    [modified_at] datetime2(7) NULL DEFAULT (getdate()),
    CONSTRAINT [PK_tb_hazard_factor] PRIMARY KEY ([id])
);
GO
INSERT INTO [tb_hazard_factor] ([id], [hazard_type], [factor_name], [category], [process], [risk_level], [measured_value], [exposure_standard], [assessment_method], [assessment_score], [cas_number], [exposure_route], [vaccination_status], [target_group], [target_count], [high_risk_count], [prevention_status], [prevention_detail], [prevention_rate], [last_check_date], [manager_name], [manager_dept], [remarks], [created_at], [modified_at]) VALUES (1, N'CHEMICAL', N'벤젠', N'유기화합물', N'도장공정', N'VERY_HIGH', N'TWA 0.48ppm', N'1ppm', NULL, NULL, N'71-43-2', NULL, NULL, NULL, NULL, NULL, N'IN_PROGRESS', N'국소배기장치 설치, 보호구 착용 의무화, 작업환경측정 분기 실시', 65, '2026-03-15 00:00:00.000', N'김안전', N'안전환경팀', N'특별관리물질, 발암성 1A', '2026-04-12 16:39:13.033', '2026-04-12 16:39:13.033');
INSERT INTO [tb_hazard_factor] ([id], [hazard_type], [factor_name], [category], [process], [risk_level], [measured_value], [exposure_standard], [assessment_method], [assessment_score], [cas_number], [exposure_route], [vaccination_status], [target_group], [target_count], [high_risk_count], [prevention_status], [prevention_detail], [prevention_rate], [last_check_date], [manager_name], [manager_dept], [remarks], [created_at], [modified_at]) VALUES (2, N'CHEMICAL', N'톨루엔', N'유기화합물', N'도장공정', N'HIGH', N'TWA 18.5ppm', N'50ppm', NULL, NULL, N'108-88-3', NULL, NULL, NULL, NULL, NULL, N'IN_PROGRESS', N'환기시설 보강, 유기용제용 방독마스크 지급', 50, '2026-03-15 00:00:00.000', N'김안전', N'안전환경팀', N'생식독성물질', '2026-04-12 16:39:13.033', '2026-04-12 16:39:13.033');
INSERT INTO [tb_hazard_factor] ([id], [hazard_type], [factor_name], [category], [process], [risk_level], [measured_value], [exposure_standard], [assessment_method], [assessment_score], [cas_number], [exposure_route], [vaccination_status], [target_group], [target_count], [high_risk_count], [prevention_status], [prevention_detail], [prevention_rate], [last_check_date], [manager_name], [manager_dept], [remarks], [created_at], [modified_at]) VALUES (3, N'CHEMICAL', N'납 및 그 무기화합물', N'금속류', N'용접공정', N'HIGH', N'TWA 0.03mg/m³', N'0.05mg/m³', NULL, NULL, N'7439-92-1', NULL, NULL, NULL, NULL, NULL, N'PLANNED', N'국소배기장치 점검, 혈중납 정기검사', 30, '2026-02-20 00:00:00.000', N'이보건', N'보건관리팀', N'특수건강진단 대상', '2026-04-12 16:39:13.033', '2026-04-12 16:39:13.033');
INSERT INTO [tb_hazard_factor] ([id], [hazard_type], [factor_name], [category], [process], [risk_level], [measured_value], [exposure_standard], [assessment_method], [assessment_score], [cas_number], [exposure_route], [vaccination_status], [target_group], [target_count], [high_risk_count], [prevention_status], [prevention_detail], [prevention_rate], [last_check_date], [manager_name], [manager_dept], [remarks], [created_at], [modified_at]) VALUES (4, N'CHEMICAL', N'크롬 및 그 화합물', N'금속류', N'도금공정', N'MEDIUM', N'TWA 0.008mg/m³', N'0.05mg/m³', NULL, NULL, N'7440-47-3', NULL, NULL, NULL, NULL, NULL, N'COMPLETED', N'밀폐설비 구축, 보호구 착용, 작업환경측정 완료', 100, '2026-03-10 00:00:00.000', N'이보건', N'보건관리팀', NULL, '2026-04-12 16:39:13.033', '2026-04-12 16:39:13.033');
INSERT INTO [tb_hazard_factor] ([id], [hazard_type], [factor_name], [category], [process], [risk_level], [measured_value], [exposure_standard], [assessment_method], [assessment_score], [cas_number], [exposure_route], [vaccination_status], [target_group], [target_count], [high_risk_count], [prevention_status], [prevention_detail], [prevention_rate], [last_check_date], [manager_name], [manager_dept], [remarks], [created_at], [modified_at]) VALUES (5, N'CHEMICAL', N'황산', N'산류', N'세척공정', N'LOW', N'TWA 0.05mg/m³', N'1mg/m³', NULL, NULL, N'7664-93-9', NULL, NULL, NULL, NULL, NULL, N'COMPLETED', N'내산성 보호구 비치, 세안설비 설치', 100, '2026-01-15 00:00:00.000', N'박환경', N'안전환경팀', NULL, '2026-04-12 16:39:13.033', '2026-04-12 16:39:13.033');
INSERT INTO [tb_hazard_factor] ([id], [hazard_type], [factor_name], [category], [process], [risk_level], [measured_value], [exposure_standard], [assessment_method], [assessment_score], [cas_number], [exposure_route], [vaccination_status], [target_group], [target_count], [high_risk_count], [prevention_status], [prevention_detail], [prevention_rate], [last_check_date], [manager_name], [manager_dept], [remarks], [created_at], [modified_at]) VALUES (6, N'CHEMICAL', N'메틸에틸케톤(MEK)', N'유기화합물', N'도장공정', N'MEDIUM', N'TWA 52ppm', N'200ppm', NULL, NULL, N'78-93-3', NULL, NULL, NULL, NULL, NULL, N'IN_PROGRESS', N'환기시설 가동, 유기용제용 보호구 지급', 70, '2026-03-15 00:00:00.000', N'김안전', N'안전환경팀', NULL, '2026-04-12 16:39:13.033', '2026-04-12 16:39:13.033');
INSERT INTO [tb_hazard_factor] ([id], [hazard_type], [factor_name], [category], [process], [risk_level], [measured_value], [exposure_standard], [assessment_method], [assessment_score], [cas_number], [exposure_route], [vaccination_status], [target_group], [target_count], [high_risk_count], [prevention_status], [prevention_detail], [prevention_rate], [last_check_date], [manager_name], [manager_dept], [remarks], [created_at], [modified_at]) VALUES (7, N'CHEMICAL', N'수산화나트륨', N'알칼리류', N'세척공정', N'LOW', N'TWA 0.5mg/m³', N'2mg/m³', NULL, NULL, N'1310-73-2', NULL, NULL, NULL, NULL, NULL, N'COMPLETED', N'내알칼리성 보호구 비치, 안전교육 실시', 100, '2026-02-10 00:00:00.000', N'박환경', N'안전환경팀', NULL, '2026-04-12 16:39:13.033', '2026-04-12 16:39:13.033');
INSERT INTO [tb_hazard_factor] ([id], [hazard_type], [factor_name], [category], [process], [risk_level], [measured_value], [exposure_standard], [assessment_method], [assessment_score], [cas_number], [exposure_route], [vaccination_status], [target_group], [target_count], [high_risk_count], [prevention_status], [prevention_detail], [prevention_rate], [last_check_date], [manager_name], [manager_dept], [remarks], [created_at], [modified_at]) VALUES (8, N'PHYSICAL', N'소음', N'소음', N'도장공정', N'VERY_HIGH', N'92.5dB(A)', N'90dB(A)', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, N'IN_PROGRESS', N'방음보호구 착용 의무화, 소음저감장치 설치 예정, 청력보존프로그램 운영', 60, '2026-03-20 00:00:00.000', N'김안전', N'안전환경팀', N'청력보존프로그램 대상', '2026-04-12 16:39:13.036', '2026-04-12 16:39:13.036');
INSERT INTO [tb_hazard_factor] ([id], [hazard_type], [factor_name], [category], [process], [risk_level], [measured_value], [exposure_standard], [assessment_method], [assessment_score], [cas_number], [exposure_route], [vaccination_status], [target_group], [target_count], [high_risk_count], [prevention_status], [prevention_detail], [prevention_rate], [last_check_date], [manager_name], [manager_dept], [remarks], [created_at], [modified_at]) VALUES (9, N'PHYSICAL', N'소음', N'소음', N'조립라인A', N'MEDIUM', N'82.3dB(A)', N'90dB(A)', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, N'COMPLETED', N'방음보호구 비치, 정기 소음측정 실시', 100, '2026-03-20 00:00:00.000', N'김안전', N'안전환경팀', NULL, '2026-04-12 16:39:13.036', '2026-04-12 16:39:13.036');
INSERT INTO [tb_hazard_factor] ([id], [hazard_type], [factor_name], [category], [process], [risk_level], [measured_value], [exposure_standard], [assessment_method], [assessment_score], [cas_number], [exposure_route], [vaccination_status], [target_group], [target_count], [high_risk_count], [prevention_status], [prevention_detail], [prevention_rate], [last_check_date], [manager_name], [manager_dept], [remarks], [created_at], [modified_at]) VALUES (10, N'PHYSICAL', N'진동', N'진동', N'연마공정', N'HIGH', N'4.2m/s²', N'5m/s²', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, N'IN_PROGRESS', N'방진장갑 지급, 진동공구 교체 검토, 작업시간 제한', 55, '2026-03-10 00:00:00.000', N'이보건', N'보건관리팀', N'국소진동 노출', '2026-04-12 16:39:13.036', '2026-04-12 16:39:13.036');
INSERT INTO [tb_hazard_factor] ([id], [hazard_type], [factor_name], [category], [process], [risk_level], [measured_value], [exposure_standard], [assessment_method], [assessment_score], [cas_number], [exposure_route], [vaccination_status], [target_group], [target_count], [high_risk_count], [prevention_status], [prevention_detail], [prevention_rate], [last_check_date], [manager_name], [manager_dept], [remarks], [created_at], [modified_at]) VALUES (11, N'PHYSICAL', N'고열', N'이상기온', N'열처리공정', N'HIGH', N'WBGT 30.2℃', N'WBGT 30℃', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, N'IN_PROGRESS', N'냉방장치 보강, 온열질환 예방교육, 휴식시간 확보', 45, '2026-03-25 00:00:00.000', N'박환경', N'안전환경팀', N'여름철 특별관리', '2026-04-12 16:39:13.036', '2026-04-12 16:39:13.036');
INSERT INTO [tb_hazard_factor] ([id], [hazard_type], [factor_name], [category], [process], [risk_level], [measured_value], [exposure_standard], [assessment_method], [assessment_score], [cas_number], [exposure_route], [vaccination_status], [target_group], [target_count], [high_risk_count], [prevention_status], [prevention_detail], [prevention_rate], [last_check_date], [manager_name], [manager_dept], [remarks], [created_at], [modified_at]) VALUES (12, N'PHYSICAL', N'방사선', N'방사선', N'비파괴검사', N'MEDIUM', N'연간 8.5mSv', N'연간 50mSv', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, N'COMPLETED', N'방사선 차폐설비, 개인선량계 착용, 정기검진', 100, '2026-02-28 00:00:00.000', N'이보건', N'보건관리팀', N'방사선작업종사자 등록', '2026-04-12 16:39:13.036', '2026-04-12 16:39:13.036');
INSERT INTO [tb_hazard_factor] ([id], [hazard_type], [factor_name], [category], [process], [risk_level], [measured_value], [exposure_standard], [assessment_method], [assessment_score], [cas_number], [exposure_route], [vaccination_status], [target_group], [target_count], [high_risk_count], [prevention_status], [prevention_detail], [prevention_rate], [last_check_date], [manager_name], [manager_dept], [remarks], [created_at], [modified_at]) VALUES (13, N'BIOLOGICAL', N'B형간염 바이러스', N'바이러스', N'의료폐기물 처리', N'HIGH', NULL, NULL, NULL, NULL, NULL, N'혈액매개', N'COMPLETED', NULL, NULL, NULL, N'IN_PROGRESS', N'예방접종 완료, 감염예방 교육, 개인보호구 착용', 80, '2026-03-01 00:00:00.000', N'이보건', N'보건관리팀', N'혈액매개 감염병', '2026-04-12 16:39:13.036', '2026-04-12 16:39:13.036');
INSERT INTO [tb_hazard_factor] ([id], [hazard_type], [factor_name], [category], [process], [risk_level], [measured_value], [exposure_standard], [assessment_method], [assessment_score], [cas_number], [exposure_route], [vaccination_status], [target_group], [target_count], [high_risk_count], [prevention_status], [prevention_detail], [prevention_rate], [last_check_date], [manager_name], [manager_dept], [remarks], [created_at], [modified_at]) VALUES (14, N'BIOLOGICAL', N'인플루엔자 바이러스', N'바이러스', N'사무실/현장 공통', N'MEDIUM', NULL, NULL, NULL, NULL, NULL, N'호흡기(비말)', N'PARTIAL', NULL, NULL, NULL, N'IN_PROGRESS', N'계절독감 예방접종 권장, 마스크 비치, 환기관리', 60, '2026-03-15 00:00:00.000', N'이보건', N'보건관리팀', N'유행시기 관리 강화', '2026-04-12 16:39:13.036', '2026-04-12 16:39:13.036');
INSERT INTO [tb_hazard_factor] ([id], [hazard_type], [factor_name], [category], [process], [risk_level], [measured_value], [exposure_standard], [assessment_method], [assessment_score], [cas_number], [exposure_route], [vaccination_status], [target_group], [target_count], [high_risk_count], [prevention_status], [prevention_detail], [prevention_rate], [last_check_date], [manager_name], [manager_dept], [remarks], [created_at], [modified_at]) VALUES (15, N'BIOLOGICAL', N'파상풍균', N'세균', N'용접/절단공정', N'MEDIUM', NULL, NULL, NULL, NULL, NULL, N'접촉(상처)', N'COMPLETED', NULL, NULL, NULL, N'COMPLETED', N'예방접종 실시, 상처관리 교육, 응급처치키트 비치', 100, '2026-02-15 00:00:00.000', N'박환경', N'안전환경팀', N'외상 위험 작업자 대상', '2026-04-12 16:39:13.036', '2026-04-12 16:39:13.036');
INSERT INTO [tb_hazard_factor] ([id], [hazard_type], [factor_name], [category], [process], [risk_level], [measured_value], [exposure_standard], [assessment_method], [assessment_score], [cas_number], [exposure_route], [vaccination_status], [target_group], [target_count], [high_risk_count], [prevention_status], [prevention_detail], [prevention_rate], [last_check_date], [manager_name], [manager_dept], [remarks], [created_at], [modified_at]) VALUES (16, N'BIOLOGICAL', N'곰팡이(진균)', N'진균', N'지하작업장', N'MEDIUM', NULL, NULL, NULL, NULL, NULL, N'호흡기(공기매개)', N'NOT_REQUIRED', NULL, NULL, NULL, N'IN_PROGRESS', N'환기시설 점검, 습도관리, 방진마스크 지급', 50, '2026-03-10 00:00:00.000', N'박환경', N'안전환경팀', N'습도 높은 작업장 관리', '2026-04-12 16:39:13.036', '2026-04-12 16:39:13.036');
INSERT INTO [tb_hazard_factor] ([id], [hazard_type], [factor_name], [category], [process], [risk_level], [measured_value], [exposure_standard], [assessment_method], [assessment_score], [cas_number], [exposure_route], [vaccination_status], [target_group], [target_count], [high_risk_count], [prevention_status], [prevention_detail], [prevention_rate], [last_check_date], [manager_name], [manager_dept], [remarks], [created_at], [modified_at]) VALUES (17, N'BIOLOGICAL', N'레지오넬라균', N'세균', N'냉각탑 관리', N'LOW', NULL, NULL, NULL, NULL, NULL, N'호흡기(에어로졸)', N'NOT_REQUIRED', NULL, NULL, NULL, N'COMPLETED', N'냉각탑 정기 청소·소독, 수질검사 실시', 100, '2026-01-20 00:00:00.000', N'박환경', N'안전환경팀', N'냉각탑 분기별 점검', '2026-04-12 16:39:13.036', '2026-04-12 16:39:13.036');
INSERT INTO [tb_hazard_factor] ([id], [hazard_type], [factor_name], [category], [process], [risk_level], [measured_value], [exposure_standard], [assessment_method], [assessment_score], [cas_number], [exposure_route], [vaccination_status], [target_group], [target_count], [high_risk_count], [prevention_status], [prevention_detail], [prevention_rate], [last_check_date], [manager_name], [manager_dept], [remarks], [created_at], [modified_at]) VALUES (18, N'ERGONOMIC', N'반복집기동작', N'반복동작', N'조립라인A', N'VERY_HIGH', NULL, NULL, N'RULA', N'6점 (조치수준 3)', NULL, NULL, NULL, NULL, NULL, NULL, N'IN_PROGRESS', N'작업대 높이 조절, 자동화설비 도입 검토, 작업순환제 실시', 40, '2026-03-20 00:00:00.000', N'이보건', N'보건관리팀', N'근골격계 유해요인조사 대상', '2026-04-12 16:39:13.040', '2026-04-12 16:39:13.040');
INSERT INTO [tb_hazard_factor] ([id], [hazard_type], [factor_name], [category], [process], [risk_level], [measured_value], [exposure_standard], [assessment_method], [assessment_score], [cas_number], [exposure_route], [vaccination_status], [target_group], [target_count], [high_risk_count], [prevention_status], [prevention_detail], [prevention_rate], [last_check_date], [manager_name], [manager_dept], [remarks], [created_at], [modified_at]) VALUES (19, N'ERGONOMIC', N'중량물 취급', N'중량물', N'물류창고', N'HIGH', NULL, NULL, N'NIOSH', N'LI 1.8', NULL, NULL, NULL, NULL, NULL, NULL, N'IN_PROGRESS', N'리프트 보조장비 도입, 중량물 취급 교육, 2인 1조 작업', 55, '2026-03-15 00:00:00.000', N'이보건', N'보건관리팀', N'25kg 이상 중량물', '2026-04-12 16:39:13.040', '2026-04-12 16:39:13.040');
INSERT INTO [tb_hazard_factor] ([id], [hazard_type], [factor_name], [category], [process], [risk_level], [measured_value], [exposure_standard], [assessment_method], [assessment_score], [cas_number], [exposure_route], [vaccination_status], [target_group], [target_count], [high_risk_count], [prevention_status], [prevention_detail], [prevention_rate], [last_check_date], [manager_name], [manager_dept], [remarks], [created_at], [modified_at]) VALUES (20, N'ERGONOMIC', N'VDT 작업', N'정적자세', N'사무직', N'MEDIUM', NULL, NULL, N'RULA', N'3점 (조치수준 1)', NULL, NULL, NULL, NULL, NULL, NULL, N'COMPLETED', N'모니터 높이 조절, 인체공학 의자 지급, 스트레칭 프로그램', 100, '2026-02-28 00:00:00.000', N'박환경', N'안전환경팀', N'사무직 전원 대상', '2026-04-12 16:39:13.040', '2026-04-12 16:39:13.040');
INSERT INTO [tb_hazard_factor] ([id], [hazard_type], [factor_name], [category], [process], [risk_level], [measured_value], [exposure_standard], [assessment_method], [assessment_score], [cas_number], [exposure_route], [vaccination_status], [target_group], [target_count], [high_risk_count], [prevention_status], [prevention_detail], [prevention_rate], [last_check_date], [manager_name], [manager_dept], [remarks], [created_at], [modified_at]) VALUES (21, N'ERGONOMIC', N'부적절한 작업자세', N'부자연스러운자세', N'용접공정', N'HIGH', NULL, NULL, N'OWAS', N'Action Category 3', NULL, NULL, NULL, NULL, NULL, NULL, N'IN_PROGRESS', N'용접지그 개선, 작업자세 교육, 보조도구 지급', 35, '2026-03-10 00:00:00.000', N'이보건', N'보건관리팀', N'장시간 고정자세 작업', '2026-04-12 16:39:13.040', '2026-04-12 16:39:13.040');
INSERT INTO [tb_hazard_factor] ([id], [hazard_type], [factor_name], [category], [process], [risk_level], [measured_value], [exposure_standard], [assessment_method], [assessment_score], [cas_number], [exposure_route], [vaccination_status], [target_group], [target_count], [high_risk_count], [prevention_status], [prevention_detail], [prevention_rate], [last_check_date], [manager_name], [manager_dept], [remarks], [created_at], [modified_at]) VALUES (22, N'ERGONOMIC', N'접촉스트레스', N'접촉스트레스', N'조립라인B', N'MEDIUM', NULL, NULL, N'RULA', N'4점 (조치수준 2)', NULL, NULL, NULL, NULL, NULL, NULL, N'PLANNED', N'작업공구 손잡이 개선, 패딩 처리, 작업순환', 20, '2026-03-05 00:00:00.000', N'이보건', N'보건관리팀', N'손·손목 부위 접촉', '2026-04-12 16:39:13.040', '2026-04-12 16:39:13.040');
INSERT INTO [tb_hazard_factor] ([id], [hazard_type], [factor_name], [category], [process], [risk_level], [measured_value], [exposure_standard], [assessment_method], [assessment_score], [cas_number], [exposure_route], [vaccination_status], [target_group], [target_count], [high_risk_count], [prevention_status], [prevention_detail], [prevention_rate], [last_check_date], [manager_name], [manager_dept], [remarks], [created_at], [modified_at]) VALUES (23, N'PSYCHOSOCIAL', N'직무 스트레스', N'직무스트레스', N'생산직 전체', N'HIGH', NULL, NULL, N'KOSS', N'상위 25%', NULL, NULL, NULL, N'생산직 근로자', 320, 45, N'IN_PROGRESS', N'스트레스 관리 프로그램 운영, EAP 상담, 근무환경 개선', 50, '2026-03-25 00:00:00.000', N'이보건', N'보건관리팀', N'연 1회 정기 평가', '2026-04-12 16:39:13.040', '2026-04-12 16:39:13.040');
INSERT INTO [tb_hazard_factor] ([id], [hazard_type], [factor_name], [category], [process], [risk_level], [measured_value], [exposure_standard], [assessment_method], [assessment_score], [cas_number], [exposure_route], [vaccination_status], [target_group], [target_count], [high_risk_count], [prevention_status], [prevention_detail], [prevention_rate], [last_check_date], [manager_name], [manager_dept], [remarks], [created_at], [modified_at]) VALUES (24, N'PSYCHOSOCIAL', N'감정노동', N'감정노동', N'고객대응업무', N'HIGH', NULL, NULL, N'감정노동평가', N'고위험', NULL, NULL, NULL, N'고객상담 직원', 45, 12, N'IN_PROGRESS', N'감정노동 보호조치, 힐링프로그램, 고충처리 창구 운영', 55, '2026-03-20 00:00:00.000', N'이보건', N'보건관리팀', N'산안법 제41조 대상', '2026-04-12 16:39:13.040', '2026-04-12 16:39:13.040');
INSERT INTO [tb_hazard_factor] ([id], [hazard_type], [factor_name], [category], [process], [risk_level], [measured_value], [exposure_standard], [assessment_method], [assessment_score], [cas_number], [exposure_route], [vaccination_status], [target_group], [target_count], [high_risk_count], [prevention_status], [prevention_detail], [prevention_rate], [last_check_date], [manager_name], [manager_dept], [remarks], [created_at], [modified_at]) VALUES (25, N'PSYCHOSOCIAL', N'직장 내 괴롭힘', N'직장내괴롭힘', N'전 부서', N'MEDIUM', NULL, NULL, N'설문조사', N'주의 수준', NULL, NULL, NULL, N'전체 임직원', 850, 8, N'IN_PROGRESS', N'예방교육 실시, 신고센터 운영, 사내규정 정비', 70, '2026-03-15 00:00:00.000', N'박환경', N'인사팀', N'근로기준법 제76조의2', '2026-04-12 16:39:13.040', '2026-04-12 16:39:13.040');
INSERT INTO [tb_hazard_factor] ([id], [hazard_type], [factor_name], [category], [process], [risk_level], [measured_value], [exposure_standard], [assessment_method], [assessment_score], [cas_number], [exposure_route], [vaccination_status], [target_group], [target_count], [high_risk_count], [prevention_status], [prevention_detail], [prevention_rate], [last_check_date], [manager_name], [manager_dept], [remarks], [created_at], [modified_at]) VALUES (26, N'PSYCHOSOCIAL', N'과로(장시간근로)', N'과로', N'교대근무조', N'HIGH', NULL, NULL, N'근로시간분석', N'월 평균 52시간 초과', NULL, NULL, NULL, N'교대근무 근로자', 180, 28, N'IN_PROGRESS', N'근무시간 관리체계 구축, 교대제 개편 검토, 건강검진 강화', 40, '2026-03-20 00:00:00.000', N'박환경', N'인사팀', N'주 52시간 초과 모니터링', '2026-04-12 16:39:13.040', '2026-04-12 16:39:13.040');
INSERT INTO [tb_hazard_factor] ([id], [hazard_type], [factor_name], [category], [process], [risk_level], [measured_value], [exposure_standard], [assessment_method], [assessment_score], [cas_number], [exposure_route], [vaccination_status], [target_group], [target_count], [high_risk_count], [prevention_status], [prevention_detail], [prevention_rate], [last_check_date], [manager_name], [manager_dept], [remarks], [created_at], [modified_at]) VALUES (27, N'PSYCHOSOCIAL', N'번아웃(소진)', N'소진', N'관리직', N'MEDIUM', NULL, NULL, N'MBI', N'중간 수준', NULL, NULL, NULL, N'관리직 직원', 120, 15, N'PLANNED', N'리더십 교육, 업무량 재조정, 휴가 사용 촉진', 25, '2026-02-28 00:00:00.000', N'이보건', N'보건관리팀', N'관리직 대상 시범 실시', '2026-04-12 16:39:13.040', '2026-04-12 16:39:13.040');
GO
-- rows: 27
